filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /hello.log
output.kafka:
  # initial brokers for reading cluster metadata
  hosts: ["192.168.0.72:9092"]

  # message topic selection + partitioning
  topic: 'hello'
  partition.round_robin:
    reachable_only: false

  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
