version: "2"
services:
  master:
    image: 172.16.0.183:8082/singularities-spark:latest
    command: start-spark master
    hostname: master
    ports:
      - "16066:6066"
      - "17070:7070"
      - "18080:8080"
      - "50070:50070"
  worker:
    image: 172.16.0.183:8082/singularities-spark:latest
    command: start-spark worker master
    environment:
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 2g
    links:
      - master