# Use postgres/example user/password credentials
version: '3.1'
services:
  postgres:
    image: postgres:9.6.14
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mariadb:
    image: mariadb:10.4.6
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  adminer:
    image: adminer:4.7.2
    restart: always
    ports: 
      - 8000:8080
  pgadmin:
    image: dpage/pgadmin4:4.11
    restart: always
    environment:
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_DEFAULT_EMAIL: user@mail.com
    ports:
      - 8001:80
volumes:
  postgres_data:
  mariadb_data:

