# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    user: "${UID}:${GID}"
    restart: always
    environment:
      POSTGRES_PASSWORD: '@Operations1'
    ports:
      - 5432:5432
    volumes:
      - $PWD/postgre/data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:6.7
    user: "${UID}:${GID}"
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: oro@winning.com.cn
      PGADMIN_DEFAULT_PASSWORD: '@Operations1'
    ports:
      - 5433:80
    volumes:
      - $PWD/pgadmin/data:/var/lib/pgadmin
