# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: @Welcome1
    ports:
      - 5432:5432
    volumes:
      - postgre_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 54320:8080
      
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: @Welcome1
    ports:
      - 54321:80
    links:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgre_data:
  pgadmin_data: