version: '2'
services:

  web:
    image: ansible/awx_web:9.3.0
    container_name: awx_web
    depends_on:
      - rabbitmq
      - memcached
      - postgres
    ports:
      - "8002:8052"
    hostname: awxweb
    user: root
    restart: unless-stopped
    volumes:
      - "$PWD/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "$PWD/environment.sh:/etc/tower/conf.d/environment.sh"
      - "$PWD/credentials.py:/etc/tower/conf.d/credentials.py"
      - "$PWD/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "$PWD/projects:/var/lib/awx/projects:rw"
      - "$PWD/road.svg:/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/ui/static/assets/logo-login.svg"
      - "$PWD/road.svg:/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/ui/static/assets/logo-header.svg"
      #- "$PWD/road.ico:/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/ui/static/assets/favicon.ico"
      #- "$PWD/road.ico:/var/lib/awx/public/static/assets/favicon.ico"
      #- "$PWD/road.ico:/var/lib/awx/public/static/favicon.ico"
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 

  task:
    image: ansible/awx_task:9.3.0
    container_name: awx_task
    depends_on:
      - rabbitmq
      - memcached
      - web
      - postgres
    hostname: awx
    user: root
    restart: unless-stopped
    volumes:
      - "$PWD/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "$PWD/environment.sh:/etc/tower/conf.d/environment.sh"
      - "$PWD/credentials.py:/etc/tower/conf.d/credentials.py"
      - "$PWD/projects:/var/lib/awx/projects:rw"
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 

  rabbitmq:
    image: ansible/awx_rabbitmq:3.7.4
    container_name: awx_rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_VHOST: "awx"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "awxpass"
      RABBITMQ_ERLANG_COOKIE: cookiemonster
      http_proxy: 
      https_proxy: 
      no_proxy: 

  memcached:
    image: "memcached:alpine"
    container_name: awx_memcached
    restart: unless-stopped
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 

  postgres:
    image: postgres:10
    container_name: awx_postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - $PWD/pgdocker/10/data/:/var/lib/postgresql/data/pgdata:Z
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass
      POSTGRES_DB: awx
      PGDATA: /var/lib/postgresql/data/pgdata
      http_proxy: 
      https_proxy: 
      no_proxy: 
