version: "2.1"
services:
  jobmanager:
    #container_name: Flink_JobManager
    image: 172.16.0.183:8082/dcs/flink:1.8.0-190602
    expose:
      - "6123"
    ports:
      - "8082:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  taskmanager:
    #container_name: Flink_TaskManager
    image: 172.16.0.183:8082/dcs/flink:1.8.0-190602
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
